### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by zwnn** [TingdiRen/URSCT-SESR#1]
## ConvI
        self.qkv = nn.Conv2d(dim, dim * 3, kernel_size=1, bias=True)
        self.qkv_dwconv = nn.Conv2d(dim * 3, dim * 3, kernel_size=3, stride=1, padding=1, groups=dim * 3, bias=True)

B_, N, C = x.shape
## ConvI
        temp = self.qkv_dwconv(self.qkv(x.permute(2,0,1))).permute(1,2,0)

我想请问为什么这里传入到卷积conv2d中的是（C,B,N）?不应该是4维的吗？

**Comment by TingdiRen** [comment]
Thanks for your question. Have you ever read the related paper? You can find that the paragraph over equation (2) illustrates the details about the shape. In practical code, for an input tensor $(1, H/P * W/P, C)$ fed into the first RCSTB, it will be multiple windows shape $(N: window num, T^2: window size^2, C)$ with Window Partition function. And I will update the code for more annotations for shape.

**Comment by zwnn** [comment]
谢谢您的解答

**Comment by zhiqiang1997** [comment]
您好，我在尝试训练时也遇到了同样的问题，请问这里该如何修改呢？

**Comment by TingdiRen** [comment]
> 您好，我在尝试训练时也遇到了同样的问题，请问这里该如何修改呢？

Thanks for your question. Without enough feedback, please describe your problem in detail.

**Comment by miracle10** [comment]
> 谢谢您的解答

您好，请问这个问题是如何解决的呢，我现在不管是运行train还是eval都会报这样的错误

`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [96, 32, 1, 1], but got 3-dimensional input of size [32, 256, 64] instead`

**Comment by WangX-v** [comment]
The 3-dimensional tensor  feed a Conv2d
-----------------------------------------------------------
self.qkv = nn.Conv2d(dim, dim * 3, kernel_size=1, bias=True)
B_, N, C = x.shape # x:(B,N,C)
temp = self.qkv_dwconv(self.qkv(x.permute(2, 0, 1))).permute(1, 2, 0)
-----------error-----------------------
Expected 4-dimensional input for 4-dimensional weight [96, 32, 1, 1], but got 3-dimensional input of size [32, 256, 64] instead

**Comment by TingdiRen** [comment]
> ## The 3-dimensional tensor feed a Conv2d
> self.qkv = nn.Conv2d(dim, dim * 3, kernel_size=1, bias=True) B_, N, C = x.shape # x:(B,N,C) temp = self.qkv_dwconv(self.qkv(x.permute(2, 0, 1))).permute(1, 2, 0) -----------error----------------------- Expected 4-dimensional input for 4-dimensional weight [96, 32, 1, 1], but got 3-dimensional input of size [32, 256, 64] instead

Actually, I don't know what you mean? If you follow the right step, the error is a disappearance.

**Comment by WangX-v** [comment]
Thank you. I'll try again

**Comment by WangX-v** [comment]
> Thank you. I'll try again
Sorry,
For the above problem, the error is caused by the inconsistent version of pytorch. Conv2d in torch1.10 can only enter 4-dimensional tensor,but torch1.11 upgrades Conv2d functionality.

**Comment by TingdiRen** [comment]
> 

Thansk for you suggestion, I'' update the tip on README.md.
