### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by miracle10** [TingdiRen/URSCT-SESR#2]
Thank you very much for your sharing. When I was running the training code, I encountered the problem of dimension mismatch. What is the reason? 
![sendpix0](https://user-images.githubusercontent.com/87251647/223972632-65df38b4-08ea-4d5e-9628-56f03cad5831.jpg)

**Comment by TingdiRen** [comment]
Sorry, the problem may be caused by upgradting. Can you provide more information about training detail? For example, the task you running? the training is dominated by default *.ymal configuration?

**Comment by miracle10** [comment]
您好，我想复现一下您的代码，我根据您提供的资源下载好了数据集，配置文件没有作任何改动，然后用您的预训练权重去训练和验证，都会报如上图所示的维度错误，若果您有时间的话希望能帮忙解答一下

**Comment by TingdiRen** [comment]
你好，我在新的设备、新的环境下进行了测试，没有遇到您所提及的问题。我重新更新了一些配置，以便进行快速入门。我的建议是您首先遵循以下步骤来了解这个rep：
1. 使用git clone拉取项目
2. 直接运行script中的Enh_train.py，以确保能使用demo数据进行训练
3. 之后替换demo数据为您的数据集进行训练
之后，你可以尝试进行测试：
1. 下载预训练权重，如UIEB的model_bestSSIM.pth
2. 将其放在exps/quickstart_Enh/models中
3. 运行script中的Enh_eval.py，以确保能调用预训练模型对demo数据进行测试
4. 之后替换demo数据为您的数据集进行测试
最后，如果你需要对预训练模型进行继续训练，请确保config设置中resume参数调整为True，并且将lr修改至较低水平（因为预训练模型是在代码更新很久前上传的，其中没有关于优化器的checkpoint）。此外，你还需要检查train.py文件中的84/85行，该代码用于加载模型权重，请确保和您放置的模型文件名称一样。
如果以上步骤还有任何问题，请再联系我，但我确信目前的版本在两台不同设备（个人和实验室服务器）上均能按照上述步骤进行运作。

**Comment by miracle10** [comment]
> 你好，我在新的设备、新的环境下进行了测试，没有遇到您所提及的问题。我重新更新了一些配置，以便进行快速入门。我的建议是您首先遵循以下步骤来了解这个rep：
> 
> 1. 使用git clone拉取项目
> 2. 直接运行script中的Enh_train.py，以确保能使用demo数据进行训练
> 3. 之后替换demo数据为您的数据集进行训练
>    之后，你可以尝试进行测试：
> 4. 下载预训练权重，如UIEB的model_bestSSIM.pth
> 5. 将其放在exps/quickstart_Enh/models中
> 6. 运行script中的Enh_eval.py，以确保能调用预训练模型对demo数据进行测试
> 7. 之后替换demo数据为您的数据集进行测试
>    最后，如果你需要对预训练模型进行继续训练，请确保config设置中resume参数调整为True，并且将lr修改至较低水平（因为预训练模型是在代码更新很久前上传的，其中没有关于优化器的checkpoint）。此外，你还需要检查train.py文件中的84/85行，该代码用于加载模型权重，请确保和您放置的模型文件名称一样。
>    如果以上步骤还有任何问题，请再联系我，但我确信目前的版本在两台不同设备（个人和实验室服务器）上均能按照上述步骤进行运作。

非常感谢您的解答，按照您的描述我又重新拉取了项目，现在已成功跑通，再次感谢您！
