### ISSUE TITLE
where is the bottleneck layers?

### ISSUE THREAD

**Issue by yu-4041** [TingdiRen/URSCT-SESR#3]

**Comment by TingdiRen** [comment]
Thanks for your question, but have you looked at the code in the "model" folder for the definition part of the model? I think a good use of search would allow you to search directly in the comments to find the content related to "bottleneck layers", which is so obvious. https://github.com/TingdiRen/URSCT-SESR/blob/cb30688bb6c579a8cf9eeed8de9cfafae67cd402/model/URSCT_model.py#L557

**Comment by yu-4041** [comment]
thank you
