### ISSUE TITLE
输入图像分辨率更改

### ISSUE THREAD

**Issue by jiaotuuuuu** [TingdiRen/URSCT-SESR#5]
您好，如果我想要改变输入图像的分辨率，而不再全部resize到256*256，且输出图像的分辨率不更改，需要更改哪些参数才能跑通呢？

**Comment by TingdiRen** [comment]
Window Size or Patch Size

**Comment by jiaotuuuuu** [comment]
但当我改完.yaml文件中的TEST_PS这个字段为1024*1024后，运行会报错：RuntimeError: shape '[1, 128, 128, 32]' is invalid for input of size 8388608，请问这是什么原因呢

**Comment by jiaotuuuuu** [comment]
明白了，WIN_SIZE和图像大小需要成比例调整，非常感谢您！
