### ISSUE TITLE
URSCT-SESR训练集测试集验证集划分

### ISSUE THREAD

**Issue by 1024AILab** [TingdiRen/URSCT-SESR#6]
请问URSCT-SESR训练集测试集验证集是如何划分的啊？有脚本吗？

**Comment by TingdiRen** [comment]
Sorry, I no longer have access to my previous workplace's server, which has now been formatted. Therefore, I'm sorry that I can't provide you with that partition. But in previous experiments, different partitions did not result in unexpected differences in performance metrics, so it should not significantly affect your reproducibility.
